import type { Achievement } from './achievement-types'

/** All 102 achievements in the game. */
export const ALL_ACHIEVEMENTS: Achievement[] = [
  // ── Getting Started (3) ──────────────────────────────
  {
    id: 'first_hand',
    name: 'First Hand',
    description: 'Complete your first training session',
    icon: '\uD83C\uDFB0',
    category: 'getting_started',
    requirement: { type: 'sessions', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'card_sharp',
    name: 'Card Sharp',
    description: 'Play 5 different training modes',
    icon: '\uD83C\uDCCF',
    category: 'getting_started',
    requirement: { type: 'mode_complete', value: 5 },
    tier: 'bronze',
  },
  {
    id: 'data_driven',
    name: 'Data Driven',
    description: 'Run your first bankroll simulation',
    icon: '\uD83D\uDCCA',
    category: 'getting_started',
    requirement: { type: 'bankroll_sim', value: 1 },
    tier: 'bronze',
  },

  // ── Dedication (8) ───────────────────────────────────
  {
    id: 'on_fire',
    name: 'On Fire',
    description: 'Train 3 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 3 },
    tier: 'bronze',
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: 'Train 7 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 7 },
    tier: 'silver',
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Train 14 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 14 },
    tier: 'gold',
  },
  {
    id: 'legendary',
    name: 'Legendary',
    description: 'Train 30 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 30 },
    tier: 'diamond',
  },
  {
    id: 'dedicated_student',
    name: 'Dedicated Student',
    description: 'Train for a total of 1 hour',
    icon: '\u23F1\uFE0F',
    category: 'dedication',
    requirement: { type: 'time', value: 60 },
    tier: 'bronze',
  },
  {
    id: 'serious_grinder',
    name: 'Serious Grinder',
    description: 'Train for a total of 10 hours',
    icon: '\u23F1\uFE0F',
    category: 'dedication',
    requirement: { type: 'time', value: 600 },
    tier: 'silver',
  },
  {
    id: 'professional_trainee',
    name: 'Professional Trainee',
    description: 'Train for a total of 50 hours',
    icon: '\u23F1\uFE0F',
    category: 'dedication',
    requirement: { type: 'time', value: 3000 },
    tier: 'gold',
  },
  {
    id: 'century',
    name: 'Century',
    description: 'Play 100 training sessions',
    icon: '\uD83C\uDFAF',
    category: 'dedication',
    requirement: { type: 'sessions', value: 100 },
    tier: 'silver',
  },
  {
    id: 'thousand_hands',
    name: 'Thousand Hands',
    description: 'Answer 1,000 flashcard questions',
    icon: '\uD83C\uDFAF',
    category: 'dedication',
    requirement: { type: 'hands', value: 1000, mode: 'deviationFlashCards' },
    tier: 'silver',
  },

  // ── Mastery (4) ──────────────────────────────────────
  {
    id: 'sharp_eye',
    name: 'Sharp Eye',
    description: 'Reach 80% accuracy in a session',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'accuracy', value: 80 },
    tier: 'bronze',
  },
  {
    id: 'precision',
    name: 'Precision',
    description: 'Reach 90% accuracy in a session',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'accuracy', value: 90 },
    tier: 'silver',
  },
  {
    id: 'sniper',
    name: 'Sniper',
    description: 'Reach 95% accuracy in a session',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'accuracy', value: 95 },
    tier: 'gold',
  },
  {
    id: 'perfection',
    name: 'Perfection',
    description: 'Score 100% in a session (min 10 questions)',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'perfect', value: 10 },
    tier: 'silver',
  },

  // ── Speed (2) ────────────────────────────────────────
  {
    id: 'quick_counter',
    name: 'Quick Counter',
    description: 'Complete Speed Drill at Normal speed with 80%+',
    icon: '\u26A1',
    category: 'speed',
    requirement: { type: 'speed', value: 1, mode: 'speedDrill' },
    tier: 'bronze',
  },
  {
    id: 'lightning_fast',
    name: 'Lightning Fast',
    description: 'Complete Speed Drill at Fast speed with 80%+',
    icon: '\u26A1',
    category: 'speed',
    requirement: { type: 'speed', value: 2, mode: 'speedDrill' },
    tier: 'silver',
  },
  // ── Counting (3) ─────────────────────────────────────
  {
    id: 'count_rookie',
    name: 'Count Rookie',
    description: 'Complete 5 Speed Drill sessions',
    icon: '\uD83D\uDD22',
    category: 'counting',
    requirement: { type: 'sessions', value: 5, mode: 'speedDrill' },
    tier: 'bronze',
  },
  {
    id: 'count_expert',
    name: 'Count Expert',
    description: 'Average 90%+ accuracy across your last 20 Speed Drill sessions',
    icon: '\uD83D\uDD22',
    category: 'counting',
    requirement: { type: 'sustained_accuracy', value: 90, mode: 'speedDrill', window: 20 },
    tier: 'gold',
  },
  {
    id: 'six_systems',
    name: 'Count Master',
    description: 'Average 95%+ accuracy across your last 30 Speed Drill sessions',
    icon: '\uD83D\uDD22',
    category: 'counting',
    requirement: { type: 'sustained_accuracy', value: 95, mode: 'speedDrill', window: 30 },
    tier: 'diamond',
  },

  // ── Deviations (3) ───────────────────────────────────
  {
    id: 'deviation_student',
    name: 'Deviation Student',
    description: 'Complete 5 Flashcards sessions',
    icon: '\uD83D\uDCCB',
    category: 'deviations',
    requirement: { type: 'sessions', value: 5, mode: 'deviationFlashCards' },
    tier: 'bronze',
  },
  {
    id: 'illustrious_18',
    name: 'Illustrious 18',
    description: '90%+ accuracy in Flashcards',
    icon: '\uD83D\uDCCB',
    category: 'deviations',
    requirement: { type: 'accuracy', value: 90, mode: 'deviationFlashCards' },
    tier: 'gold',
  },
  {
    id: 'table_general',
    name: 'Flashcard Master',
    description: '95%+ accuracy in Flashcards',
    icon: '\uD83D\uDCCB',
    category: 'deviations',
    requirement: { type: 'accuracy', value: 95, mode: 'deviationFlashCards' },
    tier: 'gold',
  },

  // ── Bet Spread & Estimation (2) ──────────────────────
  {
    id: 'spread_master',
    name: 'Spread Master',
    description: 'Average 90%+ accuracy across your last 10 Bet Spread sessions',
    icon: '\uD83D\uDCB0',
    category: 'simulation',
    requirement: { type: 'sustained_accuracy', value: 90, mode: 'betSpread', window: 10 },
    tier: 'gold',
  },
  {
    id: 'deck_hawk',
    name: 'Deck Hawk',
    description: 'Average 90%+ accuracy across your last 10 Deck Estimation sessions',
    icon: '\uD83D\uDC41',
    category: 'simulation',
    requirement: { type: 'sustained_accuracy', value: 90, mode: 'deckEstimation', window: 10 },
    tier: 'gold',
  },

  // ── Simulation (3) ───────────────────────────────────
  {
    id: 'risk_analyst',
    name: 'Risk Analyst',
    description: 'Run 5 different bankroll simulations',
    icon: '\uD83C\uDFE6',
    category: 'simulation',
    requirement: { type: 'bankroll_sim', value: 5 },
    tier: 'silver',
  },
  {
    id: 'edge_hunter',
    name: 'Edge Hunter',
    description: 'Find a configuration with >1% weighted edge',
    icon: '\uD83D\uDC8E',
    category: 'simulation',
    requirement: { type: 'bankroll_sim', value: 100 },
    tier: 'gold',
  },

  // ── Casino Session – Getting Started (3) ─────────────
  {
    id: 'casino_first_session',
    name: 'First Session',
    description: 'Complete your first Casino Session',
    icon: '\uD83C\uDFB0',
    category: 'casino_session',
    requirement: { type: 'sessions', value: 1, mode: 'casinoSession' },
    tier: 'bronze',
  },
  {
    id: 'casino_full_table',
    name: 'Full Table',
    description: 'Play a session with 5 bots at the table',
    icon: '\uD83C\uDFB0',
    category: 'casino_session',
    requirement: { type: 'casino_bots', value: 5 },
    tier: 'bronze',
  },
  {
    id: 'casino_marathon',
    name: 'Marathon',
    description: 'Play a session with 50+ hands',
    icon: '\uD83C\uDFB0',
    category: 'casino_session',
    requirement: { type: 'casino_hands', value: 50 },
    tier: 'silver',
  },

  // ── Casino Session – Grades (4) ─────────────────────
  {
    id: 'casino_passing_grade',
    name: 'Passing Grade',
    description: 'Achieve grade C or better in a Casino Session',
    icon: '\uD83D\uDCDD',
    category: 'casino_session',
    requirement: { type: 'casino_grade', value: 70 },
    tier: 'bronze',
  },
  {
    id: 'casino_honor_student',
    name: 'Honor Student',
    description: 'Achieve grade B or better in a Casino Session',
    icon: '\uD83D\uDCDD',
    category: 'casino_session',
    requirement: { type: 'casino_grade', value: 80 },
    tier: 'silver',
  },
  {
    id: 'casino_deans_list',
    name: "Dean's List",
    description: 'Achieve grade A or better in a Casino Session',
    icon: '\uD83D\uDCDD',
    category: 'casino_session',
    requirement: { type: 'casino_grade', value: 90 },
    tier: 'gold',
  },
  {
    id: 'casino_valedictorian',
    name: 'Valedictorian',
    description: 'Achieve grade A+ (95%+) in a Casino Session',
    icon: '\uD83D\uDCDD',
    category: 'casino_session',
    requirement: { type: 'casino_grade', value: 95 },
    tier: 'gold',
  },

  // ── Casino Session – Accuracy (4) ───────────────────
  {
    id: 'casino_bet_master',
    name: 'Bet Master',
    description: '90%+ Bet Accuracy in a Casino Session',
    icon: '\uD83C\uDFAF',
    category: 'casino_session',
    requirement: { type: 'casino_bet_accuracy', value: 90 },
    tier: 'gold',
  },
  {
    id: 'casino_perfect_play',
    name: 'Perfect Play',
    description: '95%+ Play Accuracy in a Casino Session',
    icon: '\uD83C\uDFAF',
    category: 'casino_session',
    requirement: { type: 'casino_play_accuracy', value: 95 },
    tier: 'gold',
  },
  {
    id: 'casino_eagle_eye',
    name: 'Eagle Eye',
    description: '90%+ Count Accuracy in a Casino Session',
    icon: '\uD83C\uDFAF',
    category: 'casino_session',
    requirement: { type: 'casino_count_accuracy', value: 90 },
    tier: 'gold',
  },
  {
    id: 'casino_triple_threat',
    name: 'Triple Threat',
    description: '90%+ in Bet, Play AND Count in a single session',
    icon: '\uD83C\uDFAF',
    category: 'casino_session',
    requirement: { type: 'casino_triple', value: 90 },
    tier: 'diamond',
  },

  // ── Casino Session – Profit (3) ─────────────────────
  {
    id: 'casino_in_the_green',
    name: 'In The Green',
    description: 'End a Casino Session with a profit',
    icon: '\uD83D\uDCB0',
    category: 'casino_session',
    requirement: { type: 'casino_profit', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'casino_high_roller',
    name: 'High Roller',
    description: 'Earn $1,000+ in a single Casino Session',
    icon: '\uD83D\uDCB0',
    category: 'casino_session',
    requirement: { type: 'casino_profit', value: 1000 },
    tier: 'silver',
  },
  {
    id: 'casino_whale',
    name: 'Whale',
    description: 'Earn $5,000+ in a single Casino Session',
    icon: '\uD83D\uDCB0',
    category: 'casino_session',
    requirement: { type: 'casino_profit', value: 5000 },
    tier: 'gold',
  },

  // ── Casino Session – Special Moments (4) ────────────
  {
    id: 'casino_natural',
    name: 'Natural',
    description: 'Get a Blackjack in a Casino Session',
    icon: '\uD83C\uDCCF',
    category: 'casino_session',
    requirement: { type: 'casino_blackjack', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'casino_hot_streak',
    name: 'Hot Streak',
    description: 'Win 5 hands in a row in a Casino Session',
    icon: '\uD83C\uDCCF',
    category: 'casino_session',
    requirement: { type: 'casino_streak', value: 5 },
    tier: 'silver',
  },
  {
    id: 'casino_splitting_aces',
    name: 'Splitting Aces',
    description: 'Split Aces in a Casino Session',
    icon: '\uD83C\uDCCF',
    category: 'casino_session',
    requirement: { type: 'casino_split_aces', value: 1 },
    tier: 'silver',
  },
  {
    id: 'casino_four_of_a_kind',
    name: 'Four of a Kind',
    description: 'Split up to 4 hands in a Casino Session',
    icon: '\uD83C\uDCCF',
    category: 'casino_session',
    requirement: { type: 'casino_max_split', value: 4 },
    tier: 'gold',
  },

  // ── Casino Session – Dedication (2) ─────────────────
  {
    id: 'casino_session_grinder',
    name: 'Session Grinder',
    description: 'Play 10 Casino Sessions',
    icon: '\uD83D\uDD25',
    category: 'casino_session',
    requirement: { type: 'sessions', value: 10, mode: 'casinoSession' },
    tier: 'silver',
  },
  {
    id: 'casino_pro',
    name: 'Casino Pro',
    description: 'Achieve grade A+ in 3 Casino Sessions',
    icon: '\uD83C\uDFC6',
    category: 'casino_session',
    requirement: { type: 'casino_grade_count', value: 3 },
    tier: 'diamond',
  },

  // ── Daily & Weekly Challenges (5) ───────────────────
  {
    id: 'first_daily',
    name: 'First Daily',
    description: 'Complete your first daily challenge',
    icon: '\u2615',
    category: 'challenges',
    requirement: { type: 'daily_completed', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'challenge_regular',
    name: 'Challenge Regular',
    description: 'Complete 10 daily challenges',
    icon: '\uD83D\uDCC5',
    category: 'challenges',
    requirement: { type: 'daily_completed', value: 10 },
    tier: 'silver',
  },
  {
    id: 'daily_devotion',
    name: 'Daily Devotion',
    description: 'Maintain a 7-day daily challenge streak',
    icon: '\uD83D\uDD25',
    category: 'challenges',
    requirement: { type: 'daily_streak', value: 7 },
    tier: 'gold',
  },
  {
    id: 'first_weekly',
    name: 'Weekly Warrior',
    description: 'Complete your first weekly challenge',
    icon: '\uD83D\uDCC6',
    category: 'challenges',
    requirement: { type: 'weekly_completed', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'weekly_master',
    name: 'Weekly Master',
    description: 'Complete 10 weekly challenges',
    icon: '\uD83C\uDFC5',
    category: 'challenges',
    requirement: { type: 'weekly_completed', value: 10 },
    tier: 'gold',
  },

  // ── Level System (5) ──────────────────────────────────
  {
    id: 'level_5',
    name: 'Rising Star',
    description: 'Reach Level 5',
    icon: '\u2B50',
    category: 'level_system',
    requirement: { type: 'reach_level', value: 5 },
    tier: 'bronze',
  },
  {
    id: 'level_10',
    name: 'Table Pro',
    description: 'Reach Level 10',
    icon: '\u2B50',
    category: 'level_system',
    requirement: { type: 'reach_level', value: 10 },
    tier: 'silver',
  },
  {
    id: 'level_15',
    name: 'Card Counter',
    description: 'Reach Level 15',
    icon: '\uD83C\uDF1F',
    category: 'level_system',
    requirement: { type: 'reach_level', value: 15 },
    tier: 'gold',
  },
  {
    id: 'level_20',
    name: 'Mastermind',
    description: 'Reach Level 20',
    icon: '\uD83C\uDF1F',
    category: 'level_system',
    requirement: { type: 'reach_level', value: 20 },
    tier: 'gold',
  },
  {
    id: 'level_25',
    name: 'Grandmaster',
    description: 'Reach Level 25 — the ultimate rank',
    icon: '\uD83D\uDC51',
    category: 'level_system',
    requirement: { type: 'reach_level', value: 25 },
    tier: 'diamond',
  },

  // ── Milestones (5) ────────────────────────────────────
  {
    id: 'five_thousand_hands',
    name: 'Five Thousand',
    description: 'Answer 5,000 total questions across all modes',
    icon: '\uD83C\uDFAF',
    category: 'milestones',
    requirement: { type: 'total_hands', value: 5000 },
    tier: 'silver',
  },
  {
    id: 'ten_thousand_hands',
    name: 'Ten Thousand',
    description: 'Answer 10,000 total questions across all modes',
    icon: '\uD83C\uDFAF',
    category: 'milestones',
    requirement: { type: 'total_hands', value: 10000 },
    tier: 'gold',
  },
  {
    id: 'twenty_hours',
    name: 'Twenty Hours',
    description: 'Train for a total of 20 hours',
    icon: '\u23F0',
    category: 'milestones',
    requirement: { type: 'total_hours', value: 20 },
    tier: 'silver',
  },
  {
    id: 'hundred_hours',
    name: 'Century of Hours',
    description: 'Train for a total of 100 hours',
    icon: '\u23F0',
    category: 'milestones',
    requirement: { type: 'total_hours', value: 100 },
    tier: 'gold',
  },
  {
    id: 'five_hundred_sessions',
    name: 'Veteran Player',
    description: 'Complete 500 training sessions',
    icon: '\uD83C\uDFC6',
    category: 'milestones',
    requirement: { type: 'sessions', value: 500 },
    tier: 'diamond',
  },

  // ── Extreme Challenges (4) ────────────────────────────
  {
    id: 'triple_perfect',
    name: 'Triple Perfect',
    description: 'Achieve 100% accuracy in 3 sessions (min 10 questions each)',
    icon: '\uD83D\uDCAF',
    category: 'extreme',
    requirement: { type: 'perfect_sessions', value: 3 },
    tier: 'gold',
  },
  {
    id: 'ten_perfects',
    name: 'Perfectionist',
    description: 'Achieve 100% accuracy in 10 sessions (min 10 questions each)',
    icon: '\uD83D\uDCAF',
    category: 'extreme',
    requirement: { type: 'perfect_sessions', value: 10 },
    tier: 'diamond',
  },
  {
    id: 'mega_profit',
    name: 'Mega Profit',
    description: 'Earn $10,000+ in a single Casino Session',
    icon: '\uD83D\uDCB5',
    category: 'extreme',
    requirement: { type: 'casino_profit', value: 10000 },
    tier: 'diamond',
  },
  {
    id: 'unstoppable_run',
    name: 'Unstoppable Run',
    description: 'Win 10 hands in a row in a Casino Session',
    icon: '\uD83D\uDD25',
    category: 'extreme',
    requirement: { type: 'casino_streak', value: 10 },
    tier: 'gold',
  },
  // ── Counting Mastery (6) ──────────────────────────────
  {
    id: 'tc_sharpshooter',
    name: 'TC Sharpshooter',
    description: '95%+ Count Accuracy in a Casino Session',
    icon: '\uD83D\uDD22',
    category: 'counting_mastery',
    requirement: { type: 'casino_count_accuracy', value: 95 },
    tier: 'gold',
  },
  {
    id: 'system_scholar',
    name: 'Estimation Expert',
    description: '95%+ accuracy in Deck Estimation',
    icon: '\uD83D\uDCDA',
    category: 'counting_mastery',
    requirement: { type: 'accuracy', value: 95, mode: 'deckEstimation' },
    tier: 'gold',
  },
  {
    id: 'counting_grinder',
    name: 'Flashcard Grinder',
    description: 'Answer 5,000 flashcard questions',
    icon: '\uD83D\uDD22',
    category: 'counting_mastery',
    requirement: { type: 'hands', value: 5000, mode: 'deviationFlashCards' },
    tier: 'gold',
  },
  {
    id: 'deviation_virtuoso',
    name: 'Deviation Virtuoso',
    description: '95%+ accuracy in Deviation Flash Cards',
    icon: '\uD83D\uDCCB',
    category: 'counting_mastery',
    requirement: { type: 'accuracy', value: 95, mode: 'deviationFlashCards' },
    tier: 'gold',
  },
  {
    id: 'master_collector',
    name: 'Master Collector',
    description: 'Unlock 50 other achievements',
    icon: '\uD83C\uDFC6',
    category: 'counting_mastery',
    requirement: { type: 'meta_unlocks', value: 50 },
    tier: 'diamond',
  },
  {
    id: 'card_counter',
    name: 'Achievement Hunter',
    description: 'Unlock 20 other achievements',
    icon: '\uD83C\uDFC6',
    category: 'counting_mastery',
    requirement: { type: 'meta_unlocks', value: 20 },
    tier: 'silver',
  },

  // ── Bankroll Tracker (17) ───────────────────────────────

  // Bronze (5)
  {
    id: 'tracker_first_session',
    name: 'First Entry',
    description: 'Log your first real casino session',
    icon: '\uD83D\uDCDD',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_sessions', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'tracker_first_win',
    name: 'First Win',
    description: 'Log your first winning casino session',
    icon: '\uD83D\uDC9A',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_first_win', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'tracker_5_sessions',
    name: 'Getting Started',
    description: 'Log 5 casino sessions',
    icon: '\uD83C\uDFB0',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_sessions', value: 5 },
    tier: 'bronze',
  },
  {
    id: 'tracker_long_session',
    name: 'Marathon Player',
    description: 'Log a session lasting 3+ hours',
    icon: '\u23F1\uFE0F',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_session_hours', value: 3 },
    tier: 'bronze',
  },

  // Silver (5)
  {
    id: 'tracker_10_sessions',
    name: 'Regular Player',
    description: 'Log 10 casino sessions',
    icon: '\uD83C\uDCCF',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_sessions', value: 10 },
    tier: 'silver',
  },
  {
    id: 'tracker_win_streak_3',
    name: 'Hot Hand',
    description: 'Win 3 casino sessions in a row',
    icon: '\uD83D\uDD25',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_win_streak', value: 3 },
    tier: 'silver',
  },
  {
    id: 'tracker_profit_1000',
    name: 'First Grand',
    description: 'Reach $1,000 total profit',
    icon: '\uD83D\uDCB0',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_total_profit', value: 1000 },
    tier: 'silver',
  },
  {
    id: 'tracker_25_hours',
    name: 'Time Investor',
    description: 'Log 25 total hours at the casino',
    icon: '\u231A',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_total_hours', value: 25 },
    tier: 'silver',
  },
  {
    id: 'tracker_comeback',
    name: 'Comeback King',
    description: 'Win a session after 3 consecutive losses',
    icon: '\uD83D\uDCAA',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_comeback', value: 3 },
    tier: 'silver',
  },

  // Gold (5)
  {
    id: 'tracker_50_sessions',
    name: 'Seasoned Player',
    description: 'Log 50 casino sessions',
    icon: '\u2660\uFE0F',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_sessions', value: 50 },
    tier: 'gold',
  },
  {
    id: 'tracker_win_streak_7',
    name: 'Red Hot',
    description: 'Win 7 casino sessions in a row',
    icon: '\uD83C\uDF1F',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_win_streak', value: 7 },
    tier: 'gold',
  },
  {
    id: 'tracker_profit_5000',
    name: 'Five Grand Club',
    description: 'Reach $5,000 total profit',
    icon: '\uD83D\uDC8E',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_total_profit', value: 5000 },
    tier: 'gold',
  },
  {
    id: 'tracker_100_hours',
    name: 'Table Centurion',
    description: 'Log 100 total hours at the casino',
    icon: '\uD83D\uDD50',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_total_hours', value: 100 },
    tier: 'gold',
  },
  {
    id: 'tracker_big_win',
    name: 'Big Night',
    description: 'Win $500+ in a single session',
    icon: '\uD83E\uDD11',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_single_session_profit', value: 500 },
    tier: 'gold',
  },

  // Diamond (2)
  {
    id: 'tracker_100_sessions',
    name: 'Casino Legend',
    description: 'Log 100 casino sessions',
    icon: '\uD83D\uDC51',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_sessions', value: 100 },
    tier: 'diamond',
  },
  {
    id: 'tracker_profit_10000',
    name: 'Ten Grand',
    description: 'Reach $10,000 total profit',
    icon: '\uD83C\uDFC6',
    category: 'bankrollTracker',
    requirement: { type: 'tracker_total_profit', value: 10000 },
    tier: 'diamond',
  },

  // ── 2026-07 balance-pass additions (11) → 100 total ──
  {
    id: 'well_rounded',
    name: 'Well-Rounded',
    description: 'Reach 80%+ accuracy in all five training modes',
    icon: '🎯',
    category: 'mastery',
    requirement: { type: 'all_modes_accuracy', value: 80 },
    tier: 'silver',
  },
  {
    id: 'renaissance_counter',
    name: 'Renaissance Counter',
    description: 'Reach 90%+ accuracy in all five training modes',
    icon: '🎓',
    category: 'mastery',
    requirement: { type: 'all_modes_accuracy', value: 90 },
    tier: 'gold',
  },
  {
    id: 'in_the_zone',
    name: 'In The Zone',
    description: 'Answer 20 questions in a row correctly in a session',
    icon: '🎯',
    category: 'mastery',
    requirement: { type: 'session_streak', value: 20 },
    tier: 'silver',
  },
  {
    id: 'unbreakable',
    name: 'Unbreakable',
    description: 'Answer 50 questions in a row correctly in a session',
    icon: '💯',
    category: 'mastery',
    requirement: { type: 'session_streak', value: 50 },
    tier: 'diamond',
  },
  {
    id: 'quick_draw',
    name: 'Quick Draw',
    description: '90%+ accuracy in a Quick Fire Deck Estimation session',
    icon: '⚡',
    category: 'counting_mastery',
    requirement: { type: 'quickfire_accuracy', value: 90 },
    tier: 'silver',
  },
  {
    id: 'blur',
    name: 'Blur',
    description: '95%+ accuracy at Fast speed in Speed Drill',
    icon: '💨',
    category: 'speed',
    requirement: { type: 'speed_accuracy', value: 95 },
    tier: 'gold',
  },
  {
    id: 'deviation_ace',
    name: 'Deviation Ace',
    description: '95%+ Deviation Accuracy in a Casino Session',
    icon: '🎯',
    category: 'casino_session',
    requirement: { type: 'casino_deviation_accuracy', value: 95 },
    tier: 'gold',
  },
  {
    id: 'marathon_mind',
    name: 'Marathon Mind',
    description: 'Train for 60+ minutes in a single session',
    icon: '⏱️',
    category: 'dedication',
    requirement: { type: 'session_duration', value: 60 },
    tier: 'silver',
  },
  {
    id: 'daily_double',
    name: 'Daily Double',
    description: 'Play all five training modes in a single day',
    icon: '☕',
    category: 'dedication',
    requirement: { type: 'modes_in_day', value: 5 },
    tier: 'bronze',
  },
  {
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Complete a training session after midnight',
    icon: '🌙',
    category: 'dedication',
    requirement: { type: 'night_session', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'platinum_collector',
    name: 'Platinum Collector',
    description: 'Unlock 75 other achievements',
    icon: '🏆',
    category: 'counting_mastery',
    requirement: { type: 'meta_unlocks', value: 75 },
    tier: 'diamond',
  },

  // ── Deviation-set mastery (enabled by per-deviation tracking) ──
  {
    id: 'fab_four_master',
    name: 'Fab Four',
    description: 'Master all four Fab 4 surrender deviations',
    icon: '🛡️',
    category: 'deviations',
    requirement: { type: 'deviation_set_mastery', value: 3, deviationSet: 'fab4' },
    tier: 'silver',
  },
  {
    id: 'deviation_sage',
    name: 'Deviation Sage',
    description: 'Master all 18 Illustrious 18 deviations',
    icon: '📜',
    category: 'deviations',
    requirement: { type: 'deviation_set_mastery', value: 3, deviationSet: 'i18' },
    tier: 'diamond',
  },
]

/** Lookup achievement by ID. */
export function getAchievementById(id: string): Achievement | undefined {
  return ALL_ACHIEVEMENTS.find(a => a.id === id)
}
