import type { Achievement } from './achievement-types'

/** All 30 achievements in the game. */
export const ALL_ACHIEVEMENTS: Achievement[] = [
  // ── Getting Started (3) ──────────────────────────────
  {
    id: 'first_hand',
    name: 'First Hand',
    description: 'Complete your first training session',
    icon: '\uD83C\uDFB0',
    category: 'getting_started',
    requirement: { type: 'sessions', value: 1 },
    tier: 'bronze',
  },
  {
    id: 'card_sharp',
    name: 'Card Sharp',
    description: 'Play 5 different training modes',
    icon: '\uD83C\uDCCF',
    category: 'getting_started',
    requirement: { type: 'mode_complete', value: 5 },
    tier: 'bronze',
  },
  {
    id: 'data_driven',
    name: 'Data Driven',
    description: 'Run your first bankroll simulation',
    icon: '\uD83D\uDCCA',
    category: 'getting_started',
    requirement: { type: 'bankroll_sim', value: 1 },
    tier: 'bronze',
  },

  // ── Dedication (8) ───────────────────────────────────
  {
    id: 'on_fire',
    name: 'On Fire',
    description: 'Train 3 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 3 },
    tier: 'bronze',
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: 'Train 7 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 7 },
    tier: 'silver',
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Train 14 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 14 },
    tier: 'gold',
  },
  {
    id: 'legendary',
    name: 'Legendary',
    description: 'Train 30 days in a row',
    icon: '\uD83D\uDD25',
    category: 'dedication',
    requirement: { type: 'streak', value: 30 },
    tier: 'diamond',
  },
  {
    id: 'dedicated_student',
    name: 'Dedicated Student',
    description: 'Train for a total of 1 hour',
    icon: '\u23F1\uFE0F',
    category: 'dedication',
    requirement: { type: 'time', value: 60 },
    tier: 'bronze',
  },
  {
    id: 'serious_grinder',
    name: 'Serious Grinder',
    description: 'Train for a total of 10 hours',
    icon: '\u23F1\uFE0F',
    category: 'dedication',
    requirement: { type: 'time', value: 600 },
    tier: 'silver',
  },
  {
    id: 'professional_trainee',
    name: 'Professional Trainee',
    description: 'Train for a total of 50 hours',
    icon: '\u23F1\uFE0F',
    category: 'dedication',
    requirement: { type: 'time', value: 3000 },
    tier: 'gold',
  },
  {
    id: 'century',
    name: 'Century',
    description: 'Play 100 training sessions',
    icon: '\uD83C\uDFAF',
    category: 'dedication',
    requirement: { type: 'sessions', value: 100 },
    tier: 'silver',
  },
  {
    id: 'thousand_hands',
    name: 'Thousand Hands',
    description: 'Play 1,000 hands in Table Counting',
    icon: '\uD83C\uDFAF',
    category: 'dedication',
    requirement: { type: 'hands', value: 1000, mode: 'tableCounting' },
    tier: 'silver',
  },

  // ── Mastery (4) ──────────────────────────────────────
  {
    id: 'sharp_eye',
    name: 'Sharp Eye',
    description: 'Reach 80% accuracy in a session',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'accuracy', value: 80 },
    tier: 'bronze',
  },
  {
    id: 'precision',
    name: 'Precision',
    description: 'Reach 90% accuracy in a session',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'accuracy', value: 90 },
    tier: 'silver',
  },
  {
    id: 'sniper',
    name: 'Sniper',
    description: 'Reach 95% accuracy in a session',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'accuracy', value: 95 },
    tier: 'gold',
  },
  {
    id: 'perfection',
    name: 'Perfection',
    description: 'Score 100% in a session (min 10 questions)',
    icon: '\u2705',
    category: 'mastery',
    requirement: { type: 'perfect', value: 10 },
    tier: 'diamond',
  },

  // ── Speed (3) ────────────────────────────────────────
  {
    id: 'quick_counter',
    name: 'Quick Counter',
    description: 'Complete Speed Drill at Normal speed with 80%+',
    icon: '\u26A1',
    category: 'speed',
    requirement: { type: 'speed', value: 1, mode: 'speedDrill' },
    tier: 'bronze',
  },
  {
    id: 'lightning_fast',
    name: 'Lightning Fast',
    description: 'Complete Speed Drill at Fast speed with 80%+',
    icon: '\u26A1',
    category: 'speed',
    requirement: { type: 'speed', value: 2, mode: 'speedDrill' },
    tier: 'silver',
  },
  {
    id: 'blitz_master',
    name: 'Blitz Master',
    description: 'Complete Speed Drill at Blitz speed with 80%+',
    icon: '\u26A1',
    category: 'speed',
    requirement: { type: 'speed', value: 3, mode: 'speedDrill' },
    tier: 'gold',
  },

  // ── Counting (3) ─────────────────────────────────────
  {
    id: 'count_rookie',
    name: 'Count Rookie',
    description: 'Complete 5 Table Counting sessions',
    icon: '\uD83D\uDD22',
    category: 'counting',
    requirement: { type: 'sessions', value: 5, mode: 'tableCounting' },
    tier: 'bronze',
  },
  {
    id: 'count_expert',
    name: 'Count Expert',
    description: '90%+ accuracy in Table Counting over 20 sessions',
    icon: '\uD83D\uDD22',
    category: 'counting',
    requirement: { type: 'accuracy', value: 90, mode: 'tableCounting' },
    tier: 'gold',
  },
  {
    id: 'six_systems',
    name: 'Six Systems',
    description: 'Train with all 6 counting systems',
    icon: '\uD83D\uDD22',
    category: 'counting',
    requirement: { type: 'mode_complete', value: 6 },
    tier: 'silver',
  },

  // ── Deviations (3) ───────────────────────────────────
  {
    id: 'deviation_student',
    name: 'Deviation Student',
    description: 'Complete 5 Deviation Training sessions',
    icon: '\uD83D\uDCCB',
    category: 'deviations',
    requirement: { type: 'sessions', value: 5, mode: 'deviationFlashCards' },
    tier: 'bronze',
  },
  {
    id: 'illustrious_18',
    name: 'Illustrious 18',
    description: '90%+ in Deviation Flash Cards',
    icon: '\uD83D\uDCCB',
    category: 'deviations',
    requirement: { type: 'accuracy', value: 90, mode: 'deviationFlashCards' },
    tier: 'gold',
  },
  {
    id: 'table_general',
    name: 'Table General',
    description: '90%+ in Deviation At Table over 10 sessions',
    icon: '\uD83D\uDCCB',
    category: 'deviations',
    requirement: { type: 'accuracy', value: 90, mode: 'deviationAtTable' },
    tier: 'gold',
  },

  // ── Bet Spread & Estimation (2) ──────────────────────
  {
    id: 'spread_master',
    name: 'Spread Master',
    description: '90%+ in Bet Spread Training over 10 sessions',
    icon: '\uD83D\uDCB0',
    category: 'simulation',
    requirement: { type: 'accuracy', value: 90, mode: 'betSpread' },
    tier: 'gold',
  },
  {
    id: 'deck_hawk',
    name: 'Deck Hawk',
    description: '90%+ in Deck Estimation over 10 sessions',
    icon: '\uD83D\uDC41',
    category: 'simulation',
    requirement: { type: 'accuracy', value: 90, mode: 'deckEstimation' },
    tier: 'gold',
  },

  // ── Simulation (3) ───────────────────────────────────
  {
    id: 'risk_analyst',
    name: 'Risk Analyst',
    description: 'Run 5 different bankroll simulations',
    icon: '\uD83C\uDFE6',
    category: 'simulation',
    requirement: { type: 'bankroll_sim', value: 5 },
    tier: 'silver',
  },
  {
    id: 'edge_hunter',
    name: 'Edge Hunter',
    description: 'Find a configuration with >1% weighted edge',
    icon: '\uD83D\uDC8E',
    category: 'simulation',
    requirement: { type: 'bankroll_sim', value: 100 },
    tier: 'gold',
  },

  // ── Ultimate (1) ─────────────────────────────────────
  {
    id: 'card_counter',
    name: 'Card Counter',
    description: 'Unlock 20 other achievements',
    icon: '\uD83C\uDFC6',
    category: 'ultimate',
    requirement: { type: 'sessions', value: 20 },
    tier: 'diamond',
  },
]

/** Lookup achievement by ID. */
export function getAchievementById(id: string): Achievement | undefined {
  return ALL_ACHIEVEMENTS.find(a => a.id === id)
}
