import type { ChallengeDefinition } from './challenge-types'

/**
 * Pool of 24 daily challenge definitions.
 *
 * Each day a deterministic hash selects one challenge from this pool.
 * Covers all training modes with escalating difficulty.
 */
export const CHALLENGE_POOL: ChallengeDefinition[] = [
  // ── Easy (50 XP) — 6 challenges ──────────────────────────────

  {
    id: 'warm_up',
    titleKey: 'chal.warm_up.title',
    descKey: 'chal.warm_up.desc',
    icon: '\u2615',
    type: 'play_sessions',
    difficulty: 'easy',
    target: 2,
    progressMode: 'cumulative_today',
  },
  {
    id: 'deal_me_in',
    titleKey: 'chal.deal_me_in.title',
    descKey: 'chal.deal_me_in.desc',
    icon: '\uD83C\uDCCF',
    type: 'play_hands',
    difficulty: 'easy',
    target: 30,
    progressMode: 'cumulative_today',
  },
  {
    id: 'quick_practice',
    titleKey: 'chal.quick_practice.title',
    descKey: 'chal.quick_practice.desc',
    icon: '\u26A1',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'speedDrill',
  },
  {
    id: 'speed_round',
    titleKey: 'chal.speed_round.title',
    descKey: 'chal.speed_round.desc',
    icon: '\uD83D\uDCB5',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'betSpread',
  },
  {
    id: 'at_the_table',
    titleKey: 'chal.at_the_table.title',
    descKey: 'chal.at_the_table.desc',
    icon: '\uD83C\uDFB4',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'deviationFlashCards',
  },
  {
    id: 'eye_test',
    titleKey: 'chal.eye_test.title',
    descKey: 'chal.eye_test.desc',
    icon: '\uD83D\uDC41',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'deckEstimation',
  },

  // ── Medium (100 XP) — 8 challenges ───────────────────────────

  {
    id: 'session_warrior',
    titleKey: 'chal.session_warrior.title',
    descKey: 'chal.session_warrior.desc',
    icon: '\u2694\uFE0F',
    type: 'play_sessions',
    difficulty: 'medium',
    target: 5,
    progressMode: 'cumulative_today',
  },
  {
    id: 'grinder',
    titleKey: 'chal.grinder.title',
    descKey: 'chal.grinder.desc',
    icon: '\uD83D\uDCAA',
    type: 'play_hands',
    difficulty: 'medium',
    target: 100,
    progressMode: 'cumulative_today',
  },
  {
    id: 'sharp_eye',
    titleKey: 'chal.sharp_eye.title',
    descKey: 'chal.sharp_eye.desc',
    icon: '\uD83D\uDC41\u200D\uD83D\uDDE8\uFE0F',
    type: 'achieve_accuracy',
    difficulty: 'medium',
    target: 80,
    progressMode: 'single_session',
  },
  {
    id: 'winning_streak',
    titleKey: 'chal.winning_streak.title',
    descKey: 'chal.winning_streak.desc',
    icon: '\uD83D\uDD25',
    type: 'win_streak',
    difficulty: 'medium',
    target: 5,
    progressMode: 'single_session',
  },
  {
    id: 'focused_practice',
    titleKey: 'chal.focused_practice.title',
    descKey: 'chal.focused_practice.desc',
    icon: '\u23F1\uFE0F',
    type: 'play_minutes',
    difficulty: 'medium',
    target: 10,
    progressMode: 'cumulative_today',
  },
  {
    id: 'deviation_day',
    titleKey: 'chal.deviation_day.title',
    descKey: 'chal.deviation_day.desc',
    icon: '\uD83C\uDFAF',
    type: 'practice_mode',
    difficulty: 'medium',
    target: 2,
    progressMode: 'cumulative_today',
    requiredMode: 'deviationFlashCards',
  },
  {
    id: 'money_management',
    titleKey: 'chal.money_management.title',
    descKey: 'chal.money_management.desc',
    icon: '\uD83D\uDCB0',
    type: 'earn_profit',
    difficulty: 'medium',
    target: 1,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
  {
    id: 'deviation_student',
    titleKey: 'chal.deviation_student.title',
    descKey: 'chal.deviation_student.desc',
    icon: '\uD83D\uDCDA',
    type: 'deviation_correct',
    difficulty: 'medium',
    target: 10,
    progressMode: 'cumulative_today',
  },

  // ── Hard (150 XP) — 6 challenges ─────────────────────────────

  {
    id: 'precision',
    titleKey: 'chal.precision.title',
    descKey: 'chal.precision.desc',
    icon: '\uD83C\uDFAF',
    type: 'achieve_accuracy',
    difficulty: 'hard',
    target: 90,
    progressMode: 'single_session',
  },
  {
    id: 'centurion',
    titleKey: 'chal.centurion.title',
    descKey: 'chal.centurion.desc',
    icon: '\uD83D\uDEE1\uFE0F',
    type: 'play_hands',
    difficulty: 'hard',
    target: 200,
    progressMode: 'cumulative_today',
  },
  {
    id: 'marathon_training',
    titleKey: 'chal.marathon_training.title',
    descKey: 'chal.marathon_training.desc',
    icon: '\uD83C\uDFC3',
    type: 'play_minutes',
    difficulty: 'hard',
    target: 30,
    progressMode: 'cumulative_today',
  },
  {
    id: 'hot_hand',
    titleKey: 'chal.hot_hand.title',
    descKey: 'chal.hot_hand.desc',
    icon: '\uD83D\uDD25',
    type: 'win_streak',
    difficulty: 'hard',
    target: 10,
    progressMode: 'single_session',
  },
  {
    id: 'big_winner',
    titleKey: 'chal.big_winner.title',
    descKey: 'chal.big_winner.desc',
    icon: '\uD83D\uDCB8',
    type: 'earn_profit',
    difficulty: 'hard',
    target: 500,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
  {
    id: 'dedicated_day',
    titleKey: 'chal.dedicated_day.title',
    descKey: 'chal.dedicated_day.desc',
    icon: '\uD83D\uDCC5',
    type: 'play_sessions',
    difficulty: 'hard',
    target: 10,
    progressMode: 'cumulative_today',
  },

  // ── Very Hard (200 XP) — 4 challenges ────────────────────────

  {
    id: 'sniper',
    titleKey: 'chal.sniper.title',
    descKey: 'chal.sniper.desc',
    icon: '\uD83C\uDFAF',
    type: 'achieve_accuracy',
    difficulty: 'very_hard',
    target: 95,
    progressMode: 'single_session',
  },
  {
    id: 'count_master',
    titleKey: 'chal.count_master.title',
    descKey: 'chal.count_master.desc',
    icon: '\uD83E\uDDE0',
    type: 'count_check',
    difficulty: 'very_hard',
    target: 90,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
  {
    id: 'lightning_speed',
    titleKey: 'chal.lightning_speed.title',
    descKey: 'chal.lightning_speed.desc',
    icon: '\u26A1',
    type: 'speed_time',
    difficulty: 'very_hard',
    target: 500,
    progressMode: 'single_session',
    requiredMode: 'speedDrill',
  },
  {
    id: 'high_roller',
    titleKey: 'chal.high_roller.title',
    descKey: 'chal.high_roller.desc',
    icon: '\uD83D\uDC8E',
    type: 'earn_profit',
    difficulty: 'very_hard',
    target: 1000,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
]
