import type { ChallengeDefinition } from './challenge-types'

/**
 * Pool of 24 daily challenge definitions.
 *
 * Each day a deterministic hash selects one challenge from this pool.
 * Covers all training modes with escalating difficulty.
 */
export const CHALLENGE_POOL: ChallengeDefinition[] = [
  // ── Easy (50 XP) — 6 challenges ──────────────────────────────

  {
    id: 'warm_up',
    title: 'Warm Up',
    description: 'Complete 2 training sessions today',
    icon: '\u2615',
    type: 'play_sessions',
    difficulty: 'easy',
    target: 2,
    progressMode: 'cumulative_today',
  },
  {
    id: 'deal_me_in',
    title: 'Deal Me In',
    description: 'Play 30 hands in any mode',
    icon: '\uD83C\uDCCF',
    type: 'play_hands',
    difficulty: 'easy',
    target: 30,
    progressMode: 'cumulative_today',
  },
  {
    id: 'quick_practice',
    title: 'Quick Practice',
    description: 'Complete a Speed Drill session',
    icon: '\u26A1',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'speedDrill',
  },
  {
    id: 'speed_round',
    title: 'Speed Round',
    description: 'Complete a Bet Spread session',
    icon: '\uD83D\uDCB5',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'betSpread',
  },
  {
    id: 'at_the_table',
    title: 'At the Table',
    description: 'Complete a Table Counting session',
    icon: '\uD83C\uDFB0',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'tableCounting',
  },
  {
    id: 'eye_test',
    title: 'Eye Test',
    description: 'Complete a Deck Estimation session',
    icon: '\uD83D\uDC41',
    type: 'practice_mode',
    difficulty: 'easy',
    target: 1,
    progressMode: 'cumulative_today',
    requiredMode: 'deckEstimation',
  },

  // ── Medium (100 XP) — 8 challenges ───────────────────────────

  {
    id: 'session_warrior',
    title: 'Session Warrior',
    description: 'Complete 5 training sessions today',
    icon: '\u2694\uFE0F',
    type: 'play_sessions',
    difficulty: 'medium',
    target: 5,
    progressMode: 'cumulative_today',
  },
  {
    id: 'grinder',
    title: 'Grinder',
    description: 'Play 100 hands in any mode',
    icon: '\uD83D\uDCAA',
    type: 'play_hands',
    difficulty: 'medium',
    target: 100,
    progressMode: 'cumulative_today',
  },
  {
    id: 'sharp_eye',
    title: 'Sharp Eye',
    description: 'Achieve 80% accuracy in a single session',
    icon: '\uD83D\uDC41\u200D\uD83D\uDDE8\uFE0F',
    type: 'achieve_accuracy',
    difficulty: 'medium',
    target: 80,
    progressMode: 'single_session',
  },
  {
    id: 'winning_streak',
    title: 'Winning Streak',
    description: 'Get a 5-answer streak in a single session',
    icon: '\uD83D\uDD25',
    type: 'win_streak',
    difficulty: 'medium',
    target: 5,
    progressMode: 'single_session',
  },
  {
    id: 'focused_practice',
    title: 'Focused Practice',
    description: 'Practice for 10 minutes total today',
    icon: '\u23F1\uFE0F',
    type: 'play_minutes',
    difficulty: 'medium',
    target: 10,
    progressMode: 'cumulative_today',
  },
  {
    id: 'deviation_day',
    title: 'Deviation Day',
    description: 'Complete 2 deviation training sessions',
    icon: '\uD83C\uDFAF',
    type: 'practice_mode',
    difficulty: 'medium',
    target: 2,
    progressMode: 'cumulative_today',
    requiredMode: 'deviationFlashCards',
  },
  {
    id: 'money_management',
    title: 'Money Management',
    description: 'Finish a Casino Session in profit',
    icon: '\uD83D\uDCB0',
    type: 'earn_profit',
    difficulty: 'medium',
    target: 1,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
  {
    id: 'deviation_student',
    title: 'Deviation Student',
    description: 'Get 10 deviation decisions correct today',
    icon: '\uD83D\uDCDA',
    type: 'deviation_correct',
    difficulty: 'medium',
    target: 10,
    progressMode: 'cumulative_today',
  },

  // ── Hard (150 XP) — 6 challenges ─────────────────────────────

  {
    id: 'precision',
    title: 'Precision',
    description: 'Achieve 90% accuracy in a single session',
    icon: '\uD83C\uDFAF',
    type: 'achieve_accuracy',
    difficulty: 'hard',
    target: 90,
    progressMode: 'single_session',
  },
  {
    id: 'centurion',
    title: 'Centurion',
    description: 'Play 200 hands in any mode',
    icon: '\uD83D\uDEE1\uFE0F',
    type: 'play_hands',
    difficulty: 'hard',
    target: 200,
    progressMode: 'cumulative_today',
  },
  {
    id: 'marathon_training',
    title: 'Marathon Training',
    description: 'Practice for 30 minutes total today',
    icon: '\uD83C\uDFC3',
    type: 'play_minutes',
    difficulty: 'hard',
    target: 30,
    progressMode: 'cumulative_today',
  },
  {
    id: 'hot_hand',
    title: 'Hot Hand',
    description: 'Get a 10-answer streak in a single session',
    icon: '\uD83D\uDD25',
    type: 'win_streak',
    difficulty: 'hard',
    target: 10,
    progressMode: 'single_session',
  },
  {
    id: 'big_winner',
    title: 'Big Winner',
    description: 'Earn $500+ profit in a Casino Session',
    icon: '\uD83D\uDCB8',
    type: 'earn_profit',
    difficulty: 'hard',
    target: 500,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
  {
    id: 'dedicated_day',
    title: 'Dedicated Day',
    description: 'Complete 10 training sessions today',
    icon: '\uD83D\uDCC5',
    type: 'play_sessions',
    difficulty: 'hard',
    target: 10,
    progressMode: 'cumulative_today',
  },

  // ── Very Hard (200 XP) — 4 challenges ────────────────────────

  {
    id: 'sniper',
    title: 'Sniper',
    description: 'Achieve 95% accuracy in a single session',
    icon: '\uD83C\uDFAF',
    type: 'achieve_accuracy',
    difficulty: 'very_hard',
    target: 95,
    progressMode: 'single_session',
  },
  {
    id: 'count_master',
    title: 'Count Master',
    description: 'Score 90%+ count accuracy in a Casino Session',
    icon: '\uD83E\uDDE0',
    type: 'count_check',
    difficulty: 'very_hard',
    target: 90,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
  {
    id: 'lightning_speed',
    title: 'Lightning Speed',
    description: 'Complete a Speed Drill under 500ms average',
    icon: '\u26A1',
    type: 'speed_time',
    difficulty: 'very_hard',
    target: 500,
    progressMode: 'single_session',
    requiredMode: 'speedDrill',
  },
  {
    id: 'high_roller',
    title: 'High Roller',
    description: 'Earn $1000+ profit in a Casino Session',
    icon: '\uD83D\uDC8E',
    type: 'earn_profit',
    difficulty: 'very_hard',
    target: 1000,
    progressMode: 'single_session',
    requiredMode: 'casinoSession',
  },
]
