import type { WeeklyChallengeDefinition } from './challenge-types'

/**
 * Pool of 16 weekly challenge definitions.
 *
 * Each week a deterministic hash selects one challenge from this pool.
 * Challenges are harder than dailies and accumulate over Mon–Sun.
 */
export const WEEKLY_CHALLENGE_POOL: WeeklyChallengeDefinition[] = [
  // ── Medium (300 XP) — 4 challenges ───────────────────────

  {
    id: 'weekly_grinder',
    titleKey: 'wchal.weekly_grinder.title',
    descKey: 'wchal.weekly_grinder.desc',
    icon: '\uD83D\uDCC5',
    type: 'play_hands',
    difficulty: 'medium',
    xpReward: 300,
    target: 200,
  },
  {
    id: 'consistent_player',
    titleKey: 'wchal.consistent_player.title',
    descKey: 'wchal.consistent_player.desc',
    icon: '\uD83D\uDCC6',
    type: 'unique_days',
    difficulty: 'medium',
    xpReward: 300,
    target: 5,
  },
  {
    id: 'mode_explorer',
    titleKey: 'wchal.mode_explorer.title',
    descKey: 'wchal.mode_explorer.desc',
    icon: '\uD83D\uDDFA\uFE0F',
    type: 'unique_modes',
    difficulty: 'medium',
    xpReward: 300,
    target: 3,
  },
  {
    id: 'weekly_practice',
    titleKey: 'wchal.weekly_practice.title',
    descKey: 'wchal.weekly_practice.desc',
    icon: '\u23F1\uFE0F',
    type: 'play_minutes',
    difficulty: 'medium',
    xpReward: 300,
    target: 120,
  },

  // ── Hard (500 XP) — 6 challenges ─────────────────────────

  {
    id: 'accuracy_week',
    titleKey: 'wchal.accuracy_week.title',
    descKey: 'wchal.accuracy_week.desc',
    icon: '\uD83C\uDFAF',
    type: 'sessions_with_accuracy',
    difficulty: 'hard',
    xpReward: 500,
    target: 5,
    minAccuracy: 85,
  },
  {
    id: 'casino_regular',
    titleKey: 'wchal.casino_regular.title',
    descKey: 'wchal.casino_regular.desc',
    icon: '\uD83C\uDFB0',
    type: 'play_sessions',
    difficulty: 'hard',
    xpReward: 500,
    target: 5,
    requiredMode: 'casinoSession',
  },
  {
    id: 'deviation_expert',
    titleKey: 'wchal.deviation_expert.title',
    descKey: 'wchal.deviation_expert.desc',
    icon: '\uD83E\uDDE0',
    type: 'deviation_correct',
    difficulty: 'hard',
    xpReward: 500,
    target: 50,
  },
  {
    id: 'marathon_week',
    titleKey: 'wchal.marathon_week.title',
    descKey: 'wchal.marathon_week.desc',
    icon: '\uD83C\uDFC3',
    type: 'play_hands',
    difficulty: 'hard',
    xpReward: 500,
    target: 500,
  },
  {
    id: 'profit_hunter',
    titleKey: 'wchal.profit_hunter.title',
    descKey: 'wchal.profit_hunter.desc',
    icon: '\uD83D\uDCB0',
    type: 'earn_profit',
    difficulty: 'hard',
    xpReward: 500,
    target: 2000,
    requiredMode: 'casinoSession',
  },
  {
    id: 'daily_warrior',
    titleKey: 'wchal.daily_warrior.title',
    descKey: 'wchal.daily_warrior.desc',
    icon: '\u2694\uFE0F',
    type: 'daily_challenges_completed',
    difficulty: 'hard',
    xpReward: 500,
    target: 7,
  },

  // ── Very Hard (800 XP) — 6 challenges ────────────────────

  {
    id: 'perfectionist_week',
    titleKey: 'wchal.perfectionist_week.title',
    descKey: 'wchal.perfectionist_week.desc',
    icon: '\uD83D\uDC8E',
    type: 'sessions_with_accuracy',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 10,
    minAccuracy: 90,
  },
  {
    id: 'ultimate_grinder',
    titleKey: 'wchal.ultimate_grinder.title',
    descKey: 'wchal.ultimate_grinder.desc',
    icon: '\uD83D\uDC51',
    type: 'play_hands',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 1000,
  },
  {
    id: 'training_addict',
    titleKey: 'wchal.training_addict.title',
    descKey: 'wchal.training_addict.desc',
    icon: '\uD83D\uDD25',
    type: 'play_minutes',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 300,
  },
  {
    id: 'all_rounder',
    titleKey: 'wchal.all_rounder.title',
    descKey: 'wchal.all_rounder.desc',
    icon: '\uD83C\uDF1F',
    type: 'unique_modes',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 7,
  },
  {
    id: 'high_roller_week',
    titleKey: 'wchal.high_roller_week.title',
    descKey: 'wchal.high_roller_week.desc',
    icon: '\uD83E\uDD11',
    type: 'earn_profit',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 5000,
    requiredMode: 'casinoSession',
  },
  {
    id: 'streak_master',
    titleKey: 'wchal.streak_master.title',
    descKey: 'wchal.streak_master.desc',
    icon: '\uD83C\uDFC6',
    type: 'win_streak',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 10,
    requiredMode: 'casinoSession',
  },
]
