import type { WeeklyChallengeDefinition } from './challenge-types'

/**
 * Pool of 16 weekly challenge definitions.
 *
 * Each week a deterministic hash selects one challenge from this pool.
 * Challenges are harder than dailies and accumulate over Mon–Sun.
 */
export const WEEKLY_CHALLENGE_POOL: WeeklyChallengeDefinition[] = [
  // ── Medium (300 XP) — 4 challenges ───────────────────────

  {
    id: 'weekly_grinder',
    title: 'Weekly Grinder',
    description: 'Play 200 hands across any modes this week',
    icon: '\uD83D\uDCC5',
    type: 'play_hands',
    difficulty: 'medium',
    xpReward: 300,
    target: 200,
  },
  {
    id: 'consistent_player',
    title: 'Consistent Player',
    description: 'Complete a training session on 5 different days',
    icon: '\uD83D\uDCC6',
    type: 'unique_days',
    difficulty: 'medium',
    xpReward: 300,
    target: 5,
  },
  {
    id: 'mode_explorer',
    title: 'Mode Explorer',
    description: 'Play at least 3 different training modes',
    icon: '\uD83D\uDDFA\uFE0F',
    type: 'unique_modes',
    difficulty: 'medium',
    xpReward: 300,
    target: 3,
  },
  {
    id: 'weekly_practice',
    title: 'Weekly Practice',
    description: 'Train for a total of 2 hours this week',
    icon: '\u23F1\uFE0F',
    type: 'play_minutes',
    difficulty: 'medium',
    xpReward: 300,
    target: 120,
  },

  // ── Hard (500 XP) — 6 challenges ─────────────────────────

  {
    id: 'accuracy_week',
    title: 'Accuracy Week',
    description: 'Achieve 85%+ accuracy in 5 separate sessions',
    icon: '\uD83C\uDFAF',
    type: 'sessions_with_accuracy',
    difficulty: 'hard',
    xpReward: 500,
    target: 5,
    minAccuracy: 85,
  },
  {
    id: 'casino_regular',
    title: 'Casino Regular',
    description: 'Play 5 Casino Sessions this week',
    icon: '\uD83C\uDFB0',
    type: 'play_sessions',
    difficulty: 'hard',
    xpReward: 500,
    target: 5,
    requiredMode: 'casinoSession',
  },
  {
    id: 'deviation_expert',
    title: 'Deviation Expert',
    description: 'Get 50 deviations correct this week',
    icon: '\uD83E\uDDE0',
    type: 'deviation_correct',
    difficulty: 'hard',
    xpReward: 500,
    target: 50,
  },
  {
    id: 'marathon_week',
    title: 'Marathon Week',
    description: 'Play 500 hands across any modes',
    icon: '\uD83C\uDFC3',
    type: 'play_hands',
    difficulty: 'hard',
    xpReward: 500,
    target: 500,
  },
  {
    id: 'profit_hunter',
    title: 'Profit Hunter',
    description: 'Earn a total of $2,000 profit in Casino Sessions',
    icon: '\uD83D\uDCB0',
    type: 'earn_profit',
    difficulty: 'hard',
    xpReward: 500,
    target: 2000,
    requiredMode: 'casinoSession',
  },
  {
    id: 'daily_warrior',
    title: 'Daily Warrior',
    description: 'Complete all 7 Daily Challenges this week',
    icon: '\u2694\uFE0F',
    type: 'daily_challenges_completed',
    difficulty: 'hard',
    xpReward: 500,
    target: 7,
  },

  // ── Very Hard (800 XP) — 6 challenges ────────────────────

  {
    id: 'perfectionist_week',
    title: 'Perfectionist Week',
    description: 'Achieve 90%+ accuracy in 10 sessions',
    icon: '\uD83D\uDC8E',
    type: 'sessions_with_accuracy',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 10,
    minAccuracy: 90,
  },
  {
    id: 'ultimate_grinder',
    title: 'Ultimate Grinder',
    description: 'Play 1,000 hands this week',
    icon: '\uD83D\uDC51',
    type: 'play_hands',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 1000,
  },
  {
    id: 'training_addict',
    title: 'Training Addict',
    description: 'Train for 5 hours this week',
    icon: '\uD83D\uDD25',
    type: 'play_minutes',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 300,
  },
  {
    id: 'all_rounder',
    title: 'All-Rounder',
    description: 'Play all 6 training modes + Casino Session',
    icon: '\uD83C\uDF1F',
    type: 'unique_modes',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 7,
  },
  {
    id: 'high_roller_week',
    title: 'High Roller Week',
    description: 'Earn $5,000 total profit in Casino Sessions',
    icon: '\uD83E\uDD11',
    type: 'earn_profit',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 5000,
    requiredMode: 'casinoSession',
  },
  {
    id: 'streak_master',
    title: 'Streak Master',
    description: 'Win 10 hands in a row in a Casino Session',
    icon: '\uD83C\uDFC6',
    type: 'win_streak',
    difficulty: 'very_hard',
    xpReward: 800,
    target: 10,
    requiredMode: 'casinoSession',
  },
]
